export default
{
    "designs": "Designs",
    "information": "Information",
    "madeBy": "Made with ❤️ by",
    "contact": "Contact",
    "languages": "Languages",
    "about": "About me",
    "experience": "Work experience",
    "skills": "Skills",
    "education": "Education",
    "social": "Social Links",
    "city": "City",
    "phone": "Phone",
    "email": "E-mail",
    "personal": "Personal Information",
    "name": "First name",
    "surname": "Last name",
    "position": "Position",
    "photo": "Photo",
    "showPhoto": "Display photo",
    "network": "Social Network",
    "socialName": "Name",
    "link": "Link",
    "institution": "Institution",
    "degree": "Degree",
    "initialDate": "Initial date",
    "finalDate": "Final date",
    "job": "Job",
    "company": "Company",
    "level": "Level"
}