export default 
{
    "designs": "Diseños",
    "information": "Información",
    "madeBy": "Hecho con ❤️ por",
    "contact": "Contacto",
    "languages": "Idiomas",
    "about": "Sobre mí",
    "experience": "Experiencia laboral",
    "skills": "Aptitudes",
    "education": "Educación",
    "social": "Redes sociales",
    "city": "Ciudad",
    "phone": "Teléfono",
    "email": "E-mail",
    "personal": "Información personal",
    "name": "Nombre",
    "surname": "Apellido",
    "position": "Posición",
    "photo": "Foto",
    "showPhoto": "Mostrar foto",
    "network": "Red social",
    "socialName": "Nombre",
    "link": "Link",
    "institution": "Institución",
    "degree": "Título",
    "initialDate": "Fecha inicio",
    "finalDate": "Fecha finalización",
    "job": "Trabajo",
    "company": "Empresa",
    "level": "Nivel",
    "summary": "Resumen",
    "January": "Ene",
    "February": "Feb",
    "March": "Mar",
    "April": "Abr",
    "May": "May",
    "June": "Jun",
    "July": "Jul",
    "August": "Ago",
    "September": "Sep",
    "October": "Oct",
    "November": "Nov",
    "December": "Dic",
    "current": "Actual"
}